//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__ADDRESS")]
	[CategoryDisplayName("Address")]
	class Address : Category
	{
		public string address;
		public string street;
		public string house_no;
		public int stories;
		public string postcode;
		public string city;
		public string region;
		public string country;
		public string description;
	}
}
