//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__CLUSTER_ADM_SERVICE")]
	[CategoryDisplayName("Administration Service")]
	class AdministrationService : Category
	{

		public enum C__CMDB__CATG__CLUSTER_ADM_SERVICE__CONNECTED_OBJECT : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int connected_object;
		public int objtype;
	}
}
