//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__AIRCRAFT")]
	[CategoryDisplayName("Aircraft")]
	class Aircraft : Category
	{
		public string registration;
		public string description;
	}
}
