//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__AC")]
	[CategoryDisplayName("Air Conditioning")]
	class AirConditioning : Category
	{

		public enum C__CATS__AC_TYPE : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int type;
		[JsonConverter(typeof(FloatDeserializer))]
		public float threshold;

		public enum C__CATS__AC_THRESHOLD_UNIT : int
		{
			C__TEMP_UNIT__CELSIUS = 1,
			C__TEMP_UNIT__FAHRENHEIT = 2,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CATS__AC_THRESHOLD_UNIT threshold_unit;

		public enum C__CATS__AC_REFRIGERATING_CAPACITY_UNIT : int
		{
			C__REF_CAPACITY_UNIT__BTU = 1,
			C__REF_CAPACITY_UNIT__KWATT = 2,
			C__REF_CAPACITY_UNIT__WATT = 3,
			C__REF_CAPACITY_UNIT__MWATT = 4,
			C__REF_CAPACITY_UNIT__GWATT = 5,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CATS__AC_REFRIGERATING_CAPACITY_UNIT capacity_unit;
		[JsonConverter(typeof(FloatDeserializer))]
		public float capacity;
		[JsonConverter(typeof(FloatDeserializer))]
		public float air_quantity;

		public enum C__CATS__AC_AIR_QUANTITY_UNIT : int
		{
			C__AC_AIR_QUANTITY_UNIT__QMH = 1,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CATS__AC_AIR_QUANTITY_UNIT air_quantity_unit;
		[JsonConverter(typeof(FloatDeserializer))]
		public float width;
		[JsonConverter(typeof(FloatDeserializer))]
		public float height;
		[JsonConverter(typeof(FloatDeserializer))]
		public float depth;

		public enum C__CATS__AC_DIMENSIONS_UNIT : int
		{
			C__DEPTH_UNIT__MM = 1,
			C__DEPTH_UNIT__CM = 2,
			C__DEPTH_UNIT__INCH = 3,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CATS__AC_DIMENSIONS_UNIT dimension_unit;
		public string description;
	}
}
