//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__APPLICATION")]
	[CategoryDisplayName("Applications")]
	class Applications : Category
	{
		public string specification;

		public enum C__CATS__APPLICATION_MANUFACTURER_ID : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int manufacturer;
		public string release;

		public enum C__CATS__APPLICATION_INSTALLATION_TYPE : int
		{
			Manuel = 1,
			Automatic = 2,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CATS__APPLICATION_INSTALLATION_TYPE installation;
		public string registration_key;
		public string install_path;
		public string description;
	}
}
