//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__ASSIGNED_LOGICAL_UNIT")]
	[CategoryDisplayName("Assigned Logical Units")]
	class AssignedLogicalUnits : Category
	{

		public enum C__CATG__ASSIGNED_LOGICAL_UNITS : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int assigned_object;
	}
}
