//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__PERSON_ASSIGNED_WORKSTATION")]
	[CategoryDisplayName("Assigned Workplaces")]
	class AssignedWorkplaces : Category
	{

		public enum C__CMDB__CATG__PERSON_ASSIGNED_WORKSTATION : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int assigned_workstations;
		public string description;
	}
}
