//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__ASSIGNED_WORKSTATION")]
	[CategoryDisplayName("Assigned Workstation")]
	class AssignedWorkstation : Category
	{

		public enum C__CMDB__CATG__LOGICAL_UNIT__PARENT : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int parent;
		public string description;
	}
}
