//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__BACKUP")]
	[CategoryDisplayName("Backup")]
	class Backup : Category
	{
		public string title;

		public enum C__CATG__BACKUP__ASSIGNED_OBJECT : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int backup;

		public enum C__CATG__BACKUP__TYPE : int
		{
			C__CMDB__BACKUP_TYPE__SNAPSHOT = 1,
			C__CMDB__BACKUP_TYPE__FILE = 2,
			C__CMDB__BACKUP_TYPE__CLONING = 3,
			C__CMDB__BACKUP_TYPE__ARCHIV = 4,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int backup_type;

		public enum C__CATG__BACKUP__CYCLE : int
		{
			C__CMDB__BACKUP_CYCLE__DAILY = 1,
			C__CMDB__BACKUP_CYCLE__WEEKLY = 2,
			C__CMDB__BACKUP_CYCLE__14_DAY = 3,
			C__CMDB__BACKUP_CYCLE__MONTHLY = 4,
			C__CMDB__BACKUP_CYCLE__YEARLY = 5,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int cycle;
		public string path_to_save;
		public string description;
	}
}
