//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__CABLE")]
	[CategoryDisplayName("Cable")]
	class Cable : Category
	{

		public enum C__CATG__CABLE_TYPE : int
		{
			C__CABLE_TYPE__CAT5 = 1,
			C__CABLE_TYPE__CAT6 = 2,
			C__CABLE_TYPE__LWL = 3,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int cable_type;

		public enum C__CATG__CABLE_COLOUR : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int cable_colour;

		public enum C__CATG__CABLE_OCCUPANCY : int
		{
			_8wired = 1,
			_4wired = 2,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int cable_occupancy;
		[JsonConverter(typeof(FloatDeserializer))]
		public float length;
		public string description;
	}
}
