//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__CERTIFICATE")]
	[CategoryDisplayName("Certificate")]
	class Certificate : Category
	{

		public enum C__CATG__CERTIFICATE__TYPE : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CATG__CERTIFICATE__TYPE type;
		public DateTime create_date;
		public DateTime expire_date;
		public string description;
	}
}
