//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__COMPUTING_RESOURCES")]
	[CategoryDisplayName("Computing Resources")]
	class ComputingResources : Category
	{
		[JsonConverter(typeof(FloatDeserializer))]
		public float ram;

		public enum C__CATG__COMPUTING_RESOURCES__RAM__MEMORY_UNIT : int
		{
			C__MEMORY_UNIT__KB = 1,
			C__MEMORY_UNIT__MB = 2,
			C__MEMORY_UNIT__GB = 3,
			C__MEMORY_UNIT__TB = 4,
			C__MEMORY_UNIT__B = 1000,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CATG__COMPUTING_RESOURCES__RAM__MEMORY_UNIT ram_unit;
		[JsonConverter(typeof(FloatDeserializer))]
		public float cpu;

		public enum C__CATG__COMPUTING_RESOURCES__CPU__FREQUENCY_UNIT : int
		{
			C__FREQUENCY_UNIT__KHZ = 1,
			C__FREQUENCY_UNIT__MHZ = 2,
			C__FREQUENCY_UNIT__GHZ = 3,
			C__FREQUENCY_UNIT__THZ = 4,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CATG__COMPUTING_RESOURCES__CPU__FREQUENCY_UNIT cpu_unit;
		[JsonConverter(typeof(FloatDeserializer))]
		public float disc_space;

		public enum C__CATG__COMPUTING_RESOURCES__DISC_SPACE__MEMORY_UNIT : int
		{
			C__MEMORY_UNIT__KB = 1,
			C__MEMORY_UNIT__MB = 2,
			C__MEMORY_UNIT__GB = 3,
			C__MEMORY_UNIT__TB = 4,
			C__MEMORY_UNIT__B = 1000,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CATG__COMPUTING_RESOURCES__DISC_SPACE__MEMORY_UNIT disc_space_unit;
		[JsonConverter(typeof(FloatDeserializer))]
		public float network_bandwidth;

		public enum C__CATG__COMPUTING_RESOURCES__NETWORK_BANDWIDTH__SPEED : int
		{
			C__PORT_SPEED__BIT_S = 1,
			C__PORT_SPEED__KBIT_S = 2,
			C__PORT_SPEED__MBIT_S = 3,
			C__PORT_SPEED__GBIT_S = 4,
			C__PORT_SPEED__NOT_SELECTED = 1000,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CATG__COMPUTING_RESOURCES__NETWORK_BANDWIDTH__SPEED network_bandwidth_unit;
		public string description;
	}
}
