//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__CONTROLLER")]
	[CategoryDisplayName("Controller")]
	class Controller : Category
	{
		public string title;

		public enum C__CATG__STORAGE_CONTROLLER_TYPE : int
		{
			SCSI = 1,
			ATA = 2,
			SATA = 3,
			PATA = 4,
			USB = 7,
			SAS = 8,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int type;

		public enum C__CATG__STORAGE_CONTROLLER_MANUFACTURER : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int manufacturer;

		public enum C__CATG__STORAGE_CONTROLLER_MODEL : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int model;
		public string description;
	}
}
