//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__CONTRACT_ASSIGNMENT")]
	[CategoryDisplayName("Contract Assignment")]
	class ContractAssignment : Category
	{

		public enum C__CATG__CONTRACT_ASSIGNMENT__CONNECTED_CONTRACTS : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int connected_contract;
		public DateTime contract_start;
		public DateTime contract_end;

		public enum C__CATG__CONTRACT_ASSIGNMENT__REACTION_RATE : int
		{
			_8x5x4 = 1,
			_24x7x4 = 2,
			Other = 3,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int reaction_rate;
		public string description;
	}
}
