//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using System.Collections.Generic;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__CPU")]
	[CategoryDisplayName("Cpu")]
	class Cpu : Category
	{
		public string title;

		public enum C__CATG__CPU_MANUFACTURER : int
		{
			AMD = 1,
			Intel = 2,
			IBM = 3,
			Motorola = 4,
			Cyrix = 5,
			VIA = 6,
			Transmeta = 7,
			SiS = 8,
			UMC = 9,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int manufacturer;

		public enum C__CATG__CPU_TYPE : int
		{
			Xeon = 1,
			Athlon = 2,
			Athlon_64 = 3,
			Pentium_III = 4,
			Pentium_IV = 5,
			Opteron = 6,
			PowerPC = 7,
			Core_2_Duo = 8,
			Core_2_Quad = 9,
			Core_2_Extreme = 10,
			Core_I7 = 11,
			Core_I7_Extreme = 12,
			Pentium = 13,
			Celeron = 14,
			Itanium = 15,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int type;
		[JsonConverter(typeof(FloatDeserializer))]
		public float frequency;

		public enum C__CATG__CPU_FREQUENCY_UNIT : int
		{
			C__FREQUENCY_UNIT__KHZ = 1,
			C__FREQUENCY_UNIT__MHZ = 2,
			C__FREQUENCY_UNIT__GHZ = 3,
			C__FREQUENCY_UNIT__THZ = 4,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CATG__CPU_FREQUENCY_UNIT frequency_unit;
		public int cores;
		public string description;

        [JsonIgnore]
	    public string cpuid;

	}
}
