//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__KRYPTO_CARD")]
	[CategoryDisplayName("Crypto Card")]
	class CryptoCard : Category
	{
		public string certificate_number;
		public string certgate_card_number;
		public string certificate_title;
		public string certificate_password;
		public DateTime certificate_procedure;
		public DateTime date_of_issue;
		public string imei_number;

		public enum C__CATS__KRYPTO_CARD__ASSIGNED_MOBILE_PHONE : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int assigned_mobile;
		public string description;
	}
}
