//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__VOIP_PHONE")]
	[CategoryDisplayName("Cucm Voip Telephone")]
	class CucmVoipTelephone : Category
	{
		public string device_protocol;
		public string description2;
		public string device_pool;
		public string common_configuration;

		public enum C__CMDB__CATG__VOIP_PHONE__BUTTON_TEMPLATE : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int button_template;

		public enum C__CMDB__CATG__VOIP_PHONE__SOFTKEY_TEMPLATE : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int softkey_template;
		public string common_profile;
		public string calling_search_space;
		public string aar_calling_search_space;
		public string media_resource_group_list;
		public string user_hold_moh_audio_source;
		public string network_hold_moh_audio_source;
		public string location;
		public string aar_group;
		public string user_locale;
		public string network_locale;
		public string built_in_bridge;
		public string privacy;
		public string device_mobility_mode;
		public string owner_user_id;
		public string phone_suite;
		public string services_provisioning;
		public string load_name;
		public string description;
	}
}
