//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__VOIP_PHONE_LINE")]
	[CategoryDisplayName("Cucm Voip Line")]
	class CucmVoipLine : Category
	{
		public string directory_number;
		public string route_partition;
		public string description2;
		public string alerting_name;
		public string ascii_alerting_name;
		public int allow_cti_control;
		public int associated_devices;
		public string voice_mail_profile;
		public string calling_search_space;
		public string presence_group;
		public string user_hold_moh_audio_source;
		public string network_hold_moh_audio_source;
		public string auto_answer;
		public string call_forward_all;
		public string sec_calling_search_space;
		public string forward_busy_internal;
		public string forward_busy_external;
		public string forward_no_answer_internal;
		public string forward_no_answer_external;
		public string forward_no_coverage_internal;
		public string forward_no_coverage_external;
		public string forward_on_cti_fail;
		public string forward_unregistered_internal;
		public string forward_unregistered_external;
		public string no_answer_ring_duration;
		public string call_pickup_group;
		public string display;
		public string ascii_display;
		public string line_text_label;
		public string ascii_line_text_label;
		public string visual_message_indicator;
		public string audible_message_indicator;
		public string ring_settings_idle;
		public string ring_settings_active;
		public string call_pickup_group_idle;
		public string call_pickup_group_active;
		public string recording_option;
		public string recording_profile;
		public string monitoring_css;
		public int log_missed_calls;
		public string external_phone_number_mask;
		public string max_number_of_calls;
		public string busy_trigger;
		public int caller_name;
		public int caller_number;
		public int redirected_number;
		public int dialed_number;
		public string description;
	}
}
