//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__DATABASE_ACCESS")]
	[CategoryDisplayName("Database Access")]
	class DatabaseAccess : Category
	{

		public enum C__CMDB__CATS__DATABASE_ACCESS__ACCESS : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int access;
	}
}
