//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__DBMS")]
	[CategoryDisplayName("Dbms")]
	class Dbms : Category
	{

		public enum C__CMDB__CATS__DBMS : int
		{
			C__DBMS__MYSQL = 1,
			C__DBMS__ORACLE = 2,
			Microsoft_SQL_Server = 3,
			C__DBMS__PGSQL = 4,
			C__DBMS__SQLITE = 5,
			C__DBMS__DB2 = 6,
			C__DBMS__LOTUSNOTES = 7,
			C__DBMS__MONGODB = 8,
			C__DBMS__MAXDB = 9,
			C__DBMS__SYBAE = 10,
			C__DBMS__DERBY = 11,
			C__DBMS__DBASE = 12,
			C__DBMS__FRONTBASE = 13,
			C__DBMS__INTERBASE = 14,
			C__DBMS__BERKELEYDB = 15,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int dbms;
		public string description;
	}
}
