//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__CLIENT")]
	[CategoryDisplayName("Desktop")]
	class Desktop : Category
	{

		public enum C__CATS__CLIENT_TYPE : int
		{
			C__CLIENT_TYPE__OTHER = 1,
			C__CLIENT_TYPE__PDA = 2,
			C__CLIENT_TYPE__PC = 3,
			C__CLIENT_TYPE__NOTEBOOK = 4,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int type;
		public string keyboard_layout;
		public string description;
	}
}
