//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__EMERGENCY_PLAN")]
	[CategoryDisplayName("Emergency Plan")]
	class EmergencyPlan : Category
	{
		public int time_needed;

		public enum C__CATS__EMERGENCY_PLAN_UNIT_OF_TIME : int
		{
			C__CMDB__UNIT_OF_TIME__SECOND = 1,
			C__CMDB__UNIT_OF_TIME__MINUTE = 2,
			C__CMDB__UNIT_OF_TIME__HOUR = 3,
			C__CMDB__UNIT_OF_TIME__DAY = 4,
			C__CMDB__UNIT_OF_TIME__MONTH = 5,
			C__CMDB__UNIT_OF_TIME__YEAR = 6,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CATS__EMERGENCY_PLAN_UNIT_OF_TIME time_unit;
		public DateTime practice_date;
		public string description;
	}
}
