//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__EPS")]
	[CategoryDisplayName("Emergency Power Supply")]
	class EmergencyPowerSupply : Category
	{

		public enum C__CMDB__CATS__POBJ_TYPE : int
		{
			C__CATS__EPS__DIESEL_GENERATOR = 1,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int type;
		public int warmup_time;

		public enum C__CMDB__CATS__EPS__WARMUP_TIME_UNIT : int
		{
			C__CMDB__UNIT_OF_TIME__SECOND = 1,
			C__CMDB__UNIT_OF_TIME__MINUTE = 2,
			C__CMDB__UNIT_OF_TIME__HOUR = 3,
			C__CMDB__UNIT_OF_TIME__DAY = 4,
			C__CMDB__UNIT_OF_TIME__MONTH = 5,
			C__CMDB__UNIT_OF_TIME__YEAR = 6,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CMDB__CATS__EPS__WARMUP_TIME_UNIT warmup_time_unit;
		public int fuel_tank;

		public enum C__CMDB__CATS__EPS__FUEL_TANK_UNIT : int
		{
			C__VOLUME_UNIT__ML = 1,
			C__VOLUME_UNIT__L = 2,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CMDB__CATS__EPS__FUEL_TANK_UNIT volume_unit;
		public int autonomy_time;

		public enum C__CMDB__CATS__EPS__AUTONOMY_TIME_UNIT : int
		{
			C__CMDB__UNIT_OF_TIME__SECOND = 1,
			C__CMDB__UNIT_OF_TIME__MINUTE = 2,
			C__CMDB__UNIT_OF_TIME__HOUR = 3,
			C__CMDB__UNIT_OF_TIME__DAY = 4,
			C__CMDB__UNIT_OF_TIME__MONTH = 5,
			C__CMDB__UNIT_OF_TIME__YEAR = 6,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CMDB__CATS__EPS__AUTONOMY_TIME_UNIT autonomy_time_unit;
		public string description;
	}
}
