//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__FILE")]
	[CategoryDisplayName("Files")]
	class Files : Category
	{

		public enum C__CATG__FILE_OBJ_FILE : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int file;
		public int revision;
		public string link;
		public string description;
	}
}
