//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__FORMFACTOR")]
	[CategoryDisplayName("Form Factor")]
	class FormFactor : Category
	{

		public enum C__CATG__FORMFACTOR_TYPE : int
		{
			C__FORMFACTOR_TYPE__19INCH = 1,
			C__FORMFACTOR_TYPE__DESKTOP = 2,
			C__FORMFACTOR_TYPE__TOWER = 3,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int formfactor;
		public int rackunits;

		public enum C__CATG__FORMFACTOR_INSTALLATION_DEPTH_UNIT : int
		{
			C__DEPTH_UNIT__MM = 1,
			C__DEPTH_UNIT__CM = 2,
			C__DEPTH_UNIT__INCH = 3,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CATG__FORMFACTOR_INSTALLATION_DEPTH_UNIT unit;
		[JsonConverter(typeof(FloatDeserializer))]
		public float width;
		[JsonConverter(typeof(FloatDeserializer))]
		public float height;
		[JsonConverter(typeof(FloatDeserializer))]
		public float depth;
		[JsonConverter(typeof(FloatDeserializer))]
		public float weight;

		public enum C__CATG__FORMFACTOR_INSTALLATION_WEIGHT_UNIT : int
		{
			C__WEIGHT_UNIT__G = 1,
			C__WEIGHT_UNIT__KG = 2,
			C__WEIGHT_UNIT__T = 3,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CATG__FORMFACTOR_INSTALLATION_WEIGHT_UNIT weight_unit;
		public string description;
	}
}
