//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__GRAPHIC")]
	[CategoryDisplayName("Graphic Card")]
	class GraphicCard : Category
	{
		public string title;

		public enum C__CATG__GRAPHIC_MANUFACTURER : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int manufacturer;
		[JsonConverter(typeof(FloatDeserializer))]
		public float memory;

		public enum C__CATG__GRAPHIC_MEMORY_UNIT : int
		{
			C__MEMORY_UNIT__KB = 1,
			C__MEMORY_UNIT__MB = 2,
			C__MEMORY_UNIT__GB = 3,
			C__MEMORY_UNIT__TB = 4,
			C__MEMORY_UNIT__B = 1000,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int unit;
		public string description;
	}
}
