//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__GROUP_MEMBERSHIPS")]
	[CategoryDisplayName("Group Memberships")]
	class GroupMemberships : Category
	{

		public enum C__CATS__GROUP__OBJECT : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int connected_object;
		public string description;
	}
}
