//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__GUEST_SYSTEMS")]
	[CategoryDisplayName("Guest Systems")]
	class GuestSystems : Category
	{

		public enum C__CATG__GUEST_SYSTEM_CONNECTED_OBJECT : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int connected_object;
		public string hostname;
		public string runs_on;
	}
}
