//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__HBA")]
	[CategoryDisplayName("Host Bus Adapter (hba)")]
	class HostBusAdapterhba : Category
	{
		public string title;

		public enum C__CATG__STORAGE_CONTROLLER_TYPE : int
		{
			C__STOR_TYPE_FC_CONTROLLER = 1,
			C__STOR_TYPE_ISCSI_CONTROLLER = 2,
			C__STOR_TYPE_SAS_CONTROLLER = 3,
			C__STOR_TYPE_SATA_CONTROLLER = 4,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CATG__STORAGE_CONTROLLER_TYPE type;

		public enum C__CATG__STORAGE_CONTROLLER_MANUFACTURER : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int manufacturer;

		public enum C__CATG__STORAGE_CONTROLLER_MODEL : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int model;
		public string description;
	}
}
