//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__DATABASE_INSTANCE")]
	[CategoryDisplayName("Instance / Oracle Database")]
	class InstanceOracleDatabase : Category
	{

		public enum C__CMDB__CATS__DATABASE_INSTANCE__DBMS : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int instance;
		public string title;
		public string listener;

		public enum C__CMDB__CATS__DATABASE_INSTANCE__CONNECTED : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int database_schema;
		public string description;
	}
}
