//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__ITS_TYPE")]
	[CategoryDisplayName("It-service Type")]
	class ItserviceType : Category
	{

		public enum C__CATG__ITS_TYPE__TYPE : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int its_type;
		public string description;
	}
}
