//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__LDAP_DN")]
	[CategoryDisplayName("Ldap")]
	class Ldap : Category
	{
		public string title;
		public string description;
	}
}
