//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__OBJECT")]
	[CategoryDisplayName("Locally Assigned Objects")]
	class LocallyAssignedObjects : Category
	{
		public string title;

		public enum C__CATG__VIRTUAL_OBJECT__ASSIGNED_OBJECTS : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int assigned_object;
	}
}
