//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__LDEV_CLIENT")]
	[CategoryDisplayName("Logical Devices (client)")]
	class LogicalDevicesclient : Category
	{
		public string title;

		public enum C__CATG__LDEVCLIENT_PATHS : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int paths;

		public enum C__CATG__LDEVCLIENT_SANPOOL : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int assigned_ldevserver;
		public int primary_path;

		public enum C__CATG__LDEVCLIENT_MULTIPATH : int
		{
			Round_Robin = 1,
			Failover = 2,
			Failback = 3,
			Weighted_Path = 4,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int multipath;
		public string description;
	}
}
