//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__LDEV_SERVER")]
	[CategoryDisplayName("Logical Devices (ldev Server)")]
	class LogicalDevicesldevServer : Category
	{
		public string title;
		public string lun;
		[JsonConverter(typeof(FloatDeserializer))]
		public float segment_size;

		public enum C__CATD__SANPOOL_UNIT : int
		{
			C__MEMORY_UNIT__KB = 1,
			C__MEMORY_UNIT__MB = 2,
			C__MEMORY_UNIT__GB = 3,
			C__MEMORY_UNIT__TB = 4,
			C__MEMORY_UNIT__B = 1000,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public C__CATD__SANPOOL_UNIT unit;
		public double capacity;

		public enum C__CATD__SANPOOL_DEVICES : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int connected_devices;
		public string paths;

		public enum C__CATD__SANPOOL_CLIENTS__MULTIPATH : int
		{
			Round_Robin = 1,
			Failover = 2,
			Failback = 3,
			Weighted_Path = 4,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int multipath;

		public enum C__CATD__SANPOOL_CLIENTS : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int ldev_clients;
		public string description;
	}
}
