//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__PERSON_GROUP_MASTER")]
	[CategoryDisplayName("Master Data")]
	class MasterData : Category
	{
		public string title;
		public string email_address;
		public string phone;
		public string ldap_group;
		public string description;
	}
}
