//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__CELL_PHONE_CONTRACT")]
	[CategoryDisplayName("Mobile Radio")]
	class MobileRadio : Category
	{
		public string imei_number;
		public string description;
	}
}
