//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__MODEL")]
	[CategoryDisplayName("Model")]
	class Model : Category
	{

		public enum C__CATG__MODEL_MANUFACTURER : int
		{
			C__MODEL_NOT_SPECIFIED = 1,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int manufacturer;

		public enum C__CATG__MODEL_TITLE_ID : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int title;
		public string productid;
		public string service_tag;
		public string serial;
		public string firmware;
		public string description;
	}
}
