//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__PASSWD")]
	[CategoryDisplayName("Passwords")]
	class Passwords : Category
	{
		public string title;
		public string username;
		public string password;
		public string description;
	}
}
