//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__ORGANIZATION_PERSONS")]
	[CategoryDisplayName("Persons")]
	class Persons : Category
	{

		public enum C__CMDB__CATS__ORGANIZATION_PERSON__OBJECT : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int @object;
		public int contact;
	}
}
