//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__POWER_SUPPLIER")]
	[CategoryDisplayName("Power Supplier")]
	class PowerSupplier : Category
	{
		public string title;
		public string volt;
		public string watt;
		public string ampere;

		public enum C__CMDB__CATG__CONNECTOR__ASSIGNED_CONNECTOR : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int assigned_connector;
		public int connector_sibling;
		public string assigned_category;
		public string description;
	}
}
