//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__ROOM")]
	[CategoryDisplayName("Room")]
	class Room : Category
	{

		public enum C__CATS__ROOM_TYPE : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int type;
		public string number;
		public string floor;
		public string description;
	}
}
