//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__ROUTER")]
	[CategoryDisplayName("Routing")]
	class Routing : Category
	{

		public enum C__CATS__ROUTER__ROUTING_PROTOCOL : int
		{
			Static = 1,
			BGP = 2,
			IGRPorEIGRP = 3,
			OSPF = 4,
			RIP = 5,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int routing_protocol;
		public int gateway_address;
		public string description;
	}
}
