//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__CHASSIS_SLOT")]
	[CategoryDisplayName("Slots")]
	class Slots : Category
	{

		public enum C__CMDB__CATS__CHASSIS_SLOT__CONNECTOR_TYPE : int
		{
			Blade_Bay = 1,
			Interconnect_Bay = 2,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int connector_type;
		public string insertion;
		public string title;
		public int from_x;
		public int to_x;
		public int from_y;
		public int to_y;
		public int assigned_devices;
		public string description;
	}
}
