//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATG__SOA_STACKS")]
	[CategoryDisplayName("Soa-stacks")]
	class Soastacks : Category
	{
		public string title;
		public int soa_stack_object;
		public int soa_stack_components;

		public enum C__CATG__SOA_STACKS__IT_SERVICE : int
		{
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int soa_stack_it_services;
		public string description;
	}
}
