//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__SWITCH_NET")]
	[CategoryDisplayName("Switch")]
	class Switch : Category
	{

		public enum C__CMDB__CATS__SWITCH_NET__VLAN : int
		{
			C__CMDB__VLAN_MANAGEMENT_PROTOCOL__VTPV2 = 1,
			C__CMDB__VLAN_MANAGEMENT_PROTOCOL__VTPV3 = 2,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int vlan;

		public enum C__CMDB__CATS__SWITCH_NET__ROLE : int
		{
			C__CMDB__SWITCH_ROLE__MASTER = 1,
			C__CMDB__SWITCH_ROLE__SLAVE = 2,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int role;

		public enum C__CMDB__CATS__SWITCH_NET__SPANNING_TREE : int
		{
			C__CMDB__SWITCH_SPANNING_TREE__STP = 1,
			C__CMDB__SWITCH_SPANNING_TREE__RSTP = 2,
			C__CMDB__SWITCH_SPANNING_TREE__MSTP = 3,
		}

		[JsonConverter(typeof(EnumDeserializer))]
		public int spanning_tree;
		public string description;
	}
}
