//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;
using u_doit.I_DoIt.Objects;
using Newtonsoft.Json;
using u_doit.I_DoIt.Objects;

namespace u_doit.Objects.Categories
{
	[CategoryId("C__CATS__APPLICATION_VARIANT")]
	[CategoryDisplayName("Variants")]
	class Variants : Category
	{
		public string title;
		public string variant;
		public string description;
	}
}
