//Generated by the u-doit class generator, written by feyris-tan.
using u_doit.I_DoIt;
using System;

namespace u_doit.Objects.Categories
{
    [CategoryId("C__CATG_U_DO_IT")]
    [CategoryDisplayName("NullCategory")]
    class NullCategory
    {

    }
}